config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  root to: 'visitors#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, :starts_at, :ends_at, presence: true
  validates :starts_at, :ends_at, overlap: true
  paginates_per 10

  belongs_to :users

  scope :all_users_tasks, ->(id) { where(user_id: id).order(starts_at: :asc)}

  def started?
    starts_at <= DateTime.now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   enum role: {typical_user: 0, admin: 1}

   has_many :tasks, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  expose(:task, attributes: :task_params)
  expose(:tasks) {Task.all_users_tasks(current_user.id).page(params[:page])}

  def create
    if task.save 
      redirect_to tasks_path, :notice => "Successfully created article."
    else
      render :new
    end
  end

  def update
    if task.save
      redirect_to(tasks_path)
    else
      render :edit
    end
  end

   def destroy
    task.destroy
    redirect_to tasks_path, :notice => "Successfully destroyed article."
  end

  private

  def task_params
    params.require(:task).permit(:name, :starts_at, :ends_at)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def date_range(start, finish)
    "#{format_datetime(start)} - #{format_datetime(finish)}"
  end

  def format_datetime(date)
    date.strftime('%d.%m.%Y %H:%M')
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Simple TODO
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body 
    .navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        .navbar-brand TODO
        ul.nav.navbar-nav
          -if (user_signed_in?)
            li 
              =link_to 'Задачи', tasks_path
            li
              =link_to 'Новая задача', new_task_path
            li.pull-right
              =link_to 'Log out', destroy_user_session_path, method: :delete
          -else
            li 
              = link_to 'Log In', new_user_session_path
            li
              = link_to 'Registration', new_user_registration_path
    .container#main
      .row
        = yield

app/views/tasks/_form.html.slim
= simple_form_for(task, html: {class: 'form-group'}) do |f|
  = f.input :name, label: 'Название'
  = f.input :starts_at, as: :datetime_picker
  = f.input :ends_at, as: :datetime_picker
  = f.button :submit

app/views/tasks/edit.html.slim
= render 'tasks/form'

app/views/tasks/index.html.slim
ul.list-group
  - tasks.each do |task|
    li.list-group-item.task-item
      = task.name
      br
      = date_range(task.starts_at, task.ends_at)
      .btn-group.pull-right.task-btn-group
        .task-item-button-group
          = button_to "Edit", edit_task_path(task), class: "btn btn-default task-edit-btn", method: 'get', disabled: task.started?
          = button_to "Delete", { action: :destroy, id: task.id }, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger task-delete-btn", disabled: task.started?



= paginate tasks

app/views/tasks/new.html.slim
= render 'tasks/form'

app/views/visitors/index.html.slim
.jumbotron
  h1 todo